{
 "title": "Insurance_system_customer_service",
 "time": { "from": "2023-12-07T14:51:04.000Z", "to": "2023-12-07T14:56:04.000Z" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "insurance_system",
     "rawSql": "SELECT AVG(cpu_usage) AS average_cpu_usage\r\nFROM (\r\n    SELECT cpu_usage\r\n    FROM insurance_system.customer_server_metric\r\n    ORDER BY timestamp DESC\r\n    LIMIT 5\r\n) AS recent_metrics;\r\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "insurance_system",
     "rawSql": "SELECT uptime\r\n    FROM insurance_system.customer_server_metric\r\n    ORDER BY timestamp DESC\r\n    LIMIT 1"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "insurance_system",
     "rawSql": "SELECT used_memory, timestamp FROM insurance_system.customer_server_metric LIMIT 50 "
    }
   ]
  },
  {
   "title": "Http Request Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "insurance_system",
     "rawSql": "SELECT AVG(http_request_count_difference) AS average_difference\r\nFROM (\r\n    SELECT http_request_count - LAG(http_request_count) OVER (ORDER BY timestamp)AS http_request_count_difference\r\n    FROM insurance_system.customer_server_metric\r\n    ORDER BY timestamp DESC\r\n    LIMIT 2\r\n) AS recent_metrics;\r\n"
    }
   ]
  }
 ]
}